### ISSUE TITLE
Expected Improvements

### ISSUE THREAD

**Issue by dev3058** [pushkardangi/stock-market-assistant#1]
![image](https://user-images.githubusercontent.com/58429743/218495572-cba9ddfb-f8a2-44aa-92fe-dfeff9f976c2.png)

**Comment by dev3058** [comment]
Fewer bugs are there 
![image](https://user-images.githubusercontent.com/58429743/218495896-a8b498cf-0330-4865-95d0-5509a28684ce.png)

**Comment by dev3058** [comment]
Need more accuracy and validations
![image](https://user-images.githubusercontent.com/58429743/218496161-44fa8413-ccfe-43e7-916c-761d3041032b.png)

**Comment by dev3058** [comment]
> Need more accuracy and validations ![image](https://user-images.githubusercontent.com/58429743/218496161-44fa8413-ccfe-43e7-916c-761d3041032b.png)

![image](https://user-images.githubusercontent.com/58429743/218496525-576ccf54-e809-42ac-a264-10117b2b8a80.png)

**Comment by pushkardangi** [comment]
Thanks for pointing out the  inaccuracy in the code. This is the initial build.  So,  I will surely work on that.

**Comment by pushkardangi** [comment]
Issues Fixed
